# Generated by Django 3.2.7 on 2021-09-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_rename_packages_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
