# Generated by Django 3.2.7 on 2021-09-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaselineitem',
            old_name='product',
            new_name='package',
        ),
    ]
