# Generated by Django 3.2.7 on 2021-09-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_product_purchaselineitem_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
