# Generated by Django 3.2.7 on 2021-09-28 07:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210928_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
